spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_test
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port:8081